import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

// eslint-config-next@15.5.13 still ships a legacy eslintrc-shaped config
// (extends/plugins/parser), not a spreadable flat-config array. Wrapping it
// with FlatCompat is the officially documented way to use it under ESLint 9
// flat config until eslint-config-next itself ships a flat export.
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is generated by Next and rewritten on every dev/build run
    // -- the file itself says it must not be edited. Next adds a triple-slash
    // reference to .next/types/routes.d.ts, which @typescript-eslint's
    // triple-slash-reference rule then rejects, so linting it means the gate
    // fails for something nobody can fix. Ignore the file, keep the rule.
    ignores: [
      ".next/**",
      "next-env.d.ts",
      "node_modules/**",
      "test-results/**",
      "playwright-report/**",
    ],
  },
];

export default eslintConfig;
